In [1]:
%matplotlib inline

import os
import IPython.display as ipd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#import ast
#Built-in module from FMA
import utils

In [2]:
filepath='C:\\Users\\ramir\\OneDrive\\Documents\\GitHub\\fma_metadata\\tracks_clean.csv'
tracks = pd.read_csv(filepath, index_col='track_id')
tracks.head()

,year_released,album,album_id,artist_id,artist,genres_top,genres_all,track,duration
track_id,,,,,,,,,
2,2009.0,AWOL - A Way Of Life,1,1,AWOL,Hip-Hop,[21],Food,168.0
3,2009.0,AWOL - A Way Of Life,1,1,AWOL,Hip-Hop,[21],Electric Ave,237.0
5,2009.0,AWOL - A Way Of Life,1,1,AWOL,Hip-Hop,[21],This World,206.0
10,2008.0,Constant Hitmaker,6,6,Kurt Vile,Pop,[10],Freeway,161.0
20,2009.0,Niris,4,4,Nicky Cook,UNKNOWN,"[17, 10, 76, 103]",Spiritual Level,311.0

In [3]:
tracks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 106018 entries, 2 to 155320
Data columns (total 9 columns):
year_released    106018 non-null float64
album            104994 non-null object
album_id         106018 non-null int64
artist_id        106018 non-null int64
artist           106018 non-null object
genres_top       106018 non-null object
genres_all       106018 non-null object
track            106017 non-null object
duration         106018 non-null float64
dtypes: float64(2), int64(2), object(5)
memory usage: 8.1+ MB

In [4]:
filepath='C:\\Users\\ramir\\OneDrive\\Documents\\GitHub\\fma_metadata\\echonest_audio_features.csv'
audio_features = pd.read_csv(filepath)
# audio_features['track_id'] = audio_features.track_id.asobject
# audio_features.index = audio_features['track_id']
# audio_features.drop('track_id', axis=1,inplace=True)
audio_features.head()

,track_id,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence
0,2,0.416675,0.675894,0.634476,0.010628,0.177647,0.159310,165.922,0.576661
1,3,0.374408,0.528643,0.817461,0.001851,0.105880,0.461818,126.957,0.269240
2,5,0.043567,0.745566,0.701470,0.000697,0.373143,0.124595,100.260,0.621661
3,10,0.951670,0.658179,0.924525,0.965427,0.115474,0.032985,111.562,0.963590
4,134,0.452217,0.513238,0.560410,0.019443,0.096567,0.525519,114.290,0.894072

In [5]:
audio_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13129 entries, 0 to 13128
Data columns (total 9 columns):
track_id            13129 non-null int64
acousticness        13129 non-null float64
danceability        13129 non-null float64
energy              13129 non-null float64
instrumentalness    13129 non-null float64
liveness            13129 non-null float64
speechiness         13129 non-null float64
tempo               13129 non-null float64
valence             13129 non-null float64
dtypes: float64(8), int64(1)
memory usage: 923.2 KB

In [6]:
audio_features.index.values

array([    0,     1,     2, ..., 13126, 13127, 13128], dtype=int64)

In [7]:
#audio_features.index = audio_features.track_id
audio_features.head()

,track_id,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence
0,2,0.416675,0.675894,0.634476,0.010628,0.177647,0.159310,165.922,0.576661
1,3,0.374408,0.528643,0.817461,0.001851,0.105880,0.461818,126.957,0.269240
2,5,0.043567,0.745566,0.701470,0.000697,0.373143,0.124595,100.260,0.621661
3,10,0.951670,0.658179,0.924525,0.965427,0.115474,0.032985,111.562,0.963590
4,134,0.452217,0.513238,0.560410,0.019443,0.096567,0.525519,114.290,0.894072

In [8]:
tracks = tracks.loc[tracks.index.isin(audio_features.index.values)]

In [9]:
tracks.head()

,year_released,album,album_id,artist_id,artist,genres_top,genres_all,track,duration
track_id,,,,,,,,,
2,2009.0,AWOL - A Way Of Life,1,1,AWOL,Hip-Hop,[21],Food,168.0
3,2009.0,AWOL - A Way Of Life,1,1,AWOL,Hip-Hop,[21],Electric Ave,237.0
5,2009.0,AWOL - A Way Of Life,1,1,AWOL,Hip-Hop,[21],This World,206.0
10,2008.0,Constant Hitmaker,6,6,Kurt Vile,Pop,[10],Freeway,161.0
20,2009.0,Niris,4,4,Nicky Cook,UNKNOWN,"[17, 10, 76, 103]",Spiritual Level,311.0

In [10]:
tracks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7527 entries, 2 to 13128
Data columns (total 9 columns):
year_released    7527 non-null float64
album            7383 non-null object
album_id         7527 non-null int64
artist_id        7527 non-null int64
artist           7527 non-null object
genres_top       7527 non-null object
genres_all       7527 non-null object
track            7527 non-null object
duration         7527 non-null float64
dtypes: float64(2), int64(2), object(5)
memory usage: 588.0+ KB

In [11]:
#pd.merge(tracks, audio_features, left_index=True, right_index=True, on=audio_features.index)
df = audio_features.join(tracks, how='inner')
df.drop(['track_id', 'track', 'album', 'album_id', 'artist_id', 'artist'], axis=1, inplace=True)
df.head()

,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence,year_released,genres_top,genres_all,duration
2,0.043567,0.745566,0.701470,0.000697,0.373143,0.124595,100.260,0.621661,2009.0,Hip-Hop,[21],168.0
3,0.951670,0.658179,0.924525,0.965427,0.115474,0.032985,111.562,0.963590,2009.0,Hip-Hop,[21],237.0
5,0.106550,0.260911,0.607067,0.835087,0.223676,0.030569,196.961,0.160267,2009.0,Hip-Hop,[21],206.0
10,0.235506,0.438672,0.487752,0.716122,0.070359,0.047298,120.790,0.650452,2008.0,Pop,[10],161.0
20,0.842113,0.285293,0.564689,0.951624,0.110481,0.040611,166.552,0.254299,2009.0,UNKNOWN,"[17, 10, 76, 103]",311.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7527 entries, 2 to 13128
Data columns (total 12 columns):
acousticness        7527 non-null float64
danceability        7527 non-null float64
energy              7527 non-null float64
instrumentalness    7527 non-null float64
liveness            7527 non-null float64
speechiness         7527 non-null float64
tempo               7527 non-null float64
valence             7527 non-null float64
year_released       7527 non-null float64
genres_top          7527 non-null object
genres_all          7527 non-null object
duration            7527 non-null float64
dtypes: float64(10), object(2)
memory usage: 764.5+ KB

In [13]:
df.to_csv('track_features_genre.csv')